export const languageList = [
  { name: "JavaScript", stars: 2 },
  { name: "Ruby", stars: 2 },
  { name: "Python", stars: 2 },
  { name: "Dart", stars: 1 },
];
export const techList = [
  "CSS",
  "HTML",
  "TypeScript",
  "Sass",
  "Bootstrap",
  "React",
  "Svelte",
  "Rails",
  "Redux",
  "Vue",
  "Vite",
  "Webpack",
  "MySQL",
  "Firebase",
  "Flutter",
  "Puppeteer",
  "Selenium",
  "Cypress",
  "Jest",
  "Figma",
  "Git",
  "Linux",
  "Godot",
];
